---

- name: Ensure that the pgbouncer packages are installed
  become: true
  apt:
    name: "pgbouncer"
    state: present
  when: not (postgresql_cluster_is_monitor | default('False') | bool)

- name: Ensure that pgbouncer is started and enabled on boot
  tags: pgbouncer
  become: true
  service:
    name: "pgbouncer"
    state: started
    enabled: yes
  when: not (postgresql_cluster_is_monitor | default('False') | bool)

- name: Template pgbouncer.ini into /etc/pgbouncer/pgbouncer.ini
  template:
    src: pgbouncer.ini.j2
    dest: /etc/pgbouncer/pgbouncer.ini
    owner: "{{ postgresql_cluster_user | default('postgres') }}"
    group: "{{ postgresql_cluster_group | default('postgres') }}"
    mode: 0600
  when: not (postgresql_cluster_is_monitor | default('False') | bool)

- name: "restart pgbouncer"
  become: true
  service:
    name: "pgbouncer"
    state: "restarted"
    enabled: yes
  when: not (postgresql_cluster_is_monitor | default('False') | bool)