---
- name: "ensure /home/postgres/.postgresql exists"
  ansible.builtin.file:
    path: /home/postgres/.postgresql
    state: directory
    owner: "postgres"
    group: "postgres"
    mode: 0700

- name: "copy key and cert to postgres user home"
  ansible.builtin.copy:
    src: "{{ postgresql_cluster_server_key | default('/data/ansible/certs/postgres_server/server.crt') }}"
    dest: "/home/postgres/.postgresql/postgresql.cert"
    owner: "postgres"
    group: "users"
    mode: 0600
    remote_src: yes

- name: "copy key and cert to postgres user home"
  ansible.builtin.copy:
    src: "{{ postgresql_cluster_server_key | default('/data/ansible/certs/postgres_server/server.crt') }}"
    dest: "/home/postgres/.postgresql/postgresql.crt"
    owner: "postgres"
    group: "users"
    mode: 0600
    remote_src: yes

- name: "copy key and cert to postgres user home"
  ansible.builtin.copy:
    src: "{{ postgresql_cluster_server_key | default('/data/ansible/certs/postgres_server/server.key') }}"
    dest: "/home/postgres/.postgresql/postgresql.key"
    owner: "postgres"
    group: "users"
    mode: 0600
    remote_src: yes