Vagrant.configure("2") do |config|
  config.vm.define :monitor do |monitor|
    monitor.vm.box = "ubuntu/bionic64"
    monitor.vm.network :private_network, ip: "10.0.0.20"
    monitor.vm.hostname = "monitor"
    monitor.vm.network :forwarded_port, guest: 22, host: 2210, id: 'ssh'
  end

  config.vm.define :node1 do |node1|
    node1.vm.box = "ubuntu/bionic64"
    node1.vm.network :private_network, ip: "10.0.0.21"
    node1.vm.hostname = "node1"
    node1.vm.network :forwarded_port, guest: 22, host: 2211, id: 'ssh'
  end

  config.vm.define :node2 do |node2|
    node2.vm.box = "ubuntu/bionic64"
    node2.vm.network :private_network, ip: "10.0.0.22"
    node2.vm.hostname = "node2"
    node2.vm.network :forwarded_port, guest: 22, host: 2212, id: 'ssh'
  end
end